INSERT INTO TipoFiltro VALUES ('Operação')
INSERT INTO TipoFiltro VALUES ('Valor Fatura')
INSERT INTO TipoFiltro VALUES ('Desconto')
INSERT INTO TipoFiltro VALUES ('Data Vencimento')
INSERT INTO TipoFiltro VALUES ('Data Início')
INSERT INTO TipoFiltro VALUES ('Data Fim')
INSERT INTO TipoFiltro VALUES ('Tempo Base')
INSERT INTO TipoFiltro VALUES ('Passo')
INSERT INTO TipoFiltro VALUES ('Baixa')
INSERT INTO TipoFiltro VALUES ('Data Baixa')
INSERT INTO TipoFiltro VALUES ('Faixa Atraso')
INSERT INTO TipoFiltro VALUES ('Estado')
INSERT INTO TipoFiltro VALUES ('Contato')
INSERT INTO TipoFiltro VALUES ('CPC')
INSERT INTO TipoFiltro VALUES ('CPC Aproveitável')
INSERT INTO TipoFiltro VALUES ('Cliente Enriquecido')
INSERT INTO TipoFiltro VALUES ('Possui Quebra')
INSERT INTO TipoFiltro VALUES ('Possui Endereço')
INSERT INTO TipoFiltro VALUES ('Possui E-Mail')
INSERT INTO TipoFiltro VALUES ('Possui Telefone')
INSERT INTO TipoFiltro VALUES ('Possui Fixo')
INSERT INTO TipoFiltro VALUES ('Possui Celular')
INSERT INTO TipoFiltro VALUES ('Vigência Acordo')
INSERT INTO TipoFiltro VALUES ('Flag Recusas')
INSERT INTO TipoFiltro VALUES ('Flag Dias PA')
INSERT INTO TipoFiltro VALUES ('Flag Ações')
INSERT INTO TipoFiltro VALUES ('Flag SMS')
INSERT INTO TipoFiltro VALUES ('Flag SMS Proventivo')
INSERT INTO TipoFiltro VALUES ('Flag SMS Boleto')
INSERT INTO TipoFiltro VALUES ('Flag WhatsApp')
INSERT INTO TipoFiltro VALUES ('Flag E-Mail')
INSERT INTO TipoFiltro VALUES ('Flag URA')
INSERT INTO TipoFiltro VALUES ('Agente Virtual')
INSERT INTO TipoFiltro VALUES ('Flag Alega Pagamento')
INSERT INTO TipoFiltro VALUES ('Flag Consta Pagamento')
INSERT INTO TipoFiltro VALUES ('Flag Suspeita de Fraude')
